name: Test
on:
  workflow_dispatch: # Allows triggering manually

permissions:
  issues: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/issues \
            -f title="Test" \
            -f body="Ping @Infinisil-s-Test-Organization/test"
        env:
          # This token has write access to only issues to create one
          GH_TOKEN: ${{ github.token }}
