name: Test
on:
  workflow_dispatch: # Allows triggering manually

permissions:
  issues: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v26

      - uses: actions/checkout@v4
        with:
          path: repo

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Generate issue body
        run: repo/scripts/review-body.sh repo ${{ github.repository }} > body
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/issues \
            -f title="Test" \
            -F body=@body
        env:
          # This token has write access to only issues to create one
          GH_TOKEN: ${{ github.token }}
